spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=metadatadb
    username: admin
    password: admin
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update